apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-z4wg
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0011-tenant/tkrw-pr712-0075-0011-app/devfile-sample-z4wg@sha256:d87c5f136233dddcb36919c2383f3767c38af2a99dfe5d3f9c638796cb48a42a
        name: my-nodejs
        resources: {}
status: {}
